document.getElementById('buenosAires').addEventListener("click",function(){
    window.location.href="BuenosAires.html";
})
document.getElementById('ciudadDeMexico').addEventListener("click",function(){
    window.location.href="CiudadDeMexico.html";
})
document.getElementById('quito').addEventListener("click",function(){
    window.location.href="Quito.html";
})
document.getElementById('saoPaulo').addEventListener("click",function(){
    window.location.href="SaoPaulo.html";
})
